# Generated by Django 5.2.1 on 2025-06-17 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField()),
                ('columns', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PayerCodeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payers', models.CharField(max_length=100)),
                ('payor_category', models.CharField(max_length=100)),
                ('edits', models.TextField()),
                ('remarks', models.TextField()),
                ('l_codes', models.TextField(verbose_name='L Codes')),
                ('l_codes_instructions', models.TextField(verbose_name='L Codes Instructions')),
                ('e_codes', models.TextField(verbose_name='E Codes')),
                ('e_codes_instructions', models.TextField(verbose_name='E Codes Instructions')),
                ('a_codes', models.TextField(verbose_name='A Codes')),
                ('a_codes_instructions', models.TextField(verbose_name='A Codes Instructions')),
                ('k_codes', models.TextField(verbose_name='K Codes')),
                ('k_codes_instructions', models.TextField(verbose_name='K Codes Instructions')),
                ('dummy_field', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='rcm_app.excelupload')),
            ],
        ),
    ]
