# Generated by Django 5.2.1 on 2025-06-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payercodeinfo',
            name='dummy_field',
        ),
        migrations.AlterField(
            model_name='payercodeinfo',
            name='a_codes',
            field=models.TextField(blank=True, null=True, verbose_name='A Codes'),
        ),
        migrations.AlterField(
            model_name='payercodeinfo',
            name='a_codes_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='A Codes Instructions'),
        ),
        migrations.AlterField(
            model_name='payercodeinfo',
            name='e_codes',
            field=models.TextField(blank=True, null=True, verbose_name='E Codes'),
        ),
        migrations.AlterField(
            model_name='payercodeinfo',
            name='e_codes_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='E Codes Instructions'),
        ),
        migrations.AlterField(
            model_name='payercodeinfo',
            name='edits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payercodeinfo',
            name='k_codes',
            field=models.TextField(blank=True, null=True, verbose_name='K Codes'),
        ),
        migrations.AlterField(
            model_name='payercodeinfo',
            name='k_codes_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='K Codes Instructions'),
        ),
        migrations.AlterField(
            model_name='payercodeinfo',
            name='l_codes',
            field=models.TextField(blank=True, null=True, verbose_name='L Codes'),
        ),
        migrations.AlterField(
            model_name='payercodeinfo',
            name='l_codes_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='L Codes Instructions'),
        ),
        migrations.AlterField(
            model_name='payercodeinfo',
            name='payers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payercodeinfo',
            name='payor_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payercodeinfo',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
