# Generated by Django 5.2.1 on 2025-06-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcm_app', '0003_payercodeinfo_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='payercodeinfo',
            name='cpt_edits_sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payercodeinfo',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
