# Generated by Django 5.2.1 on 2025-06-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcm_app', '0004_payercodeinfo_cpt_edits_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payercodeinfo',
            name='billing_coding_instructions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
