# Generated by Django 5.2.1 on 2025-06-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcm_app', '0005_payercodeinfo_billing_coding_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='payercodeinfo',
            name='edit_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payercodeinfo',
            name='enter_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
